export type MachineType = "Skid Steer" | "Compact Track Loader"
export type LiftPath = "Radial" | "Vertical"

export interface SkidSteer {
  slug: string
  brand: string
  model: string
  type: MachineType
  ratedOperatingCapacity: number // lbs
  tippingLoad: number // lbs
  engineHp: number
  operatingWeight: number // lbs
  bucketWidth: number // inches
  travelSpeed: number // mph
  hydraulicFlow: number // gpm (standard flow)
  priceRange: string
  msrp?: number // USD, where publicly available
  liftPath: LiftPath
  description: string
  highlights: string[]
}

export const machines: SkidSteer[] = [
  // ─── BOBCAT ──────────────────────────────────────────────────────────────────
  {
    slug: "bobcat-s70",
    brand: "Bobcat",
    model: "S70",
    type: "Skid Steer",
    ratedOperatingCapacity: 760,
    tippingLoad: 1520,
    engineHp: 23.5,
    operatingWeight: 3053,
    bucketWidth: 48,
    travelSpeed: 6.1,
    hydraulicFlow: 9.9,
    liftPath: "Radial",
    priceRange: "$28,000–$36,000",
    description: "The world's smallest skid steer — fits through a standard door. Ideal for interior demolition, landscaping, and confined-site work.",
    highlights: ["23.5 HP Kubota diesel", "Bob-Tach system", "48\" standard bucket width", "Fits through 36\" doorway"],
  },
  {
    slug: "bobcat-s450",
    brand: "Bobcat",
    model: "S450",
    type: "Skid Steer",
    ratedOperatingCapacity: 1300,
    tippingLoad: 2600,
    engineHp: 55,
    operatingWeight: 5989,
    bucketWidth: 60,
    travelSpeed: 7.7,
    hydraulicFlow: 18.4,
    liftPath: "Radial",
    priceRange: "$44,000–$54,000",
    description: "Compact mid-frame skid steer with Bobcat's signature radial lift path and broad attachment compatibility.",
    highlights: ["Bob-Tach quick coupler", "Selectable joystick controls", "Pressurized cab option", "High-flow available"],
  },
  {
    slug: "bobcat-s550",
    brand: "Bobcat",
    model: "S550",
    type: "Skid Steer",
    ratedOperatingCapacity: 1595,
    tippingLoad: 3190,
    engineHp: 60,
    operatingWeight: 6725,
    bucketWidth: 64,
    travelSpeed: 7.4,
    hydraulicFlow: 21.5,
    liftPath: "Radial",
    priceRange: "$50,000–$62,000",
    description: "A popular mid-size skid steer balancing power, size, and jobsite versatility for landscaping and construction.",
    highlights: ["60 HP Bobcat diesel", "Attachment Control System", "2-speed travel", "Bob-Tach system"],
  },
  {
    slug: "bobcat-s650",
    brand: "Bobcat",
    model: "S650",
    type: "Skid Steer",
    ratedOperatingCapacity: 2200,
    tippingLoad: 4400,
    engineHp: 66,
    operatingWeight: 7070,
    bucketWidth: 68,
    travelSpeed: 7.4,
    hydraulicFlow: 26.6,
    liftPath: "Radial",
    priceRange: "$57,000–$70,000",
    description: "Large-frame radial lift workhorse with a wide range of heavy-duty attachments and proven reliability.",
    highlights: ["66 HP diesel", "Selectable joystick controls", "Enhanced cab visibility", "Attachment Control System"],
  },
  {
    slug: "bobcat-s740",
    brand: "Bobcat",
    model: "S740",
    type: "Skid Steer",
    ratedOperatingCapacity: 2600,
    tippingLoad: 5200,
    engineHp: 90,
    operatingWeight: 9340,
    bucketWidth: 72,
    travelSpeed: 7.4,
    hydraulicFlow: 30.6,
    liftPath: "Vertical",
    priceRange: "$72,000–$88,000",
    description: "Bobcat's large vertical-lift skid steer delivering extended reach and exceptional truck-loading height.",
    highlights: ["Vertical lift path", "90 HP engine", "30.6 gpm standard / 40.8 gpm high-flow", "Ride Control standard"],
  },
  {
    slug: "bobcat-s770",
    brand: "Bobcat",
    model: "S770",
    type: "Skid Steer",
    ratedOperatingCapacity: 3200,
    tippingLoad: 6400,
    engineHp: 100,
    operatingWeight: 10890,
    bucketWidth: 80,
    travelSpeed: 12.0,
    hydraulicFlow: 32.0,
    liftPath: "Vertical",
    priceRange: "$88,000–$108,000",
    description: "Bobcat's flagship skid steer — maximum capacity, two-speed travel, and top-tier vertical lift reach.",
    highlights: ["2-speed 12 mph max", "100 HP engine", "Vertical lift for truck loading", "Optional pressurized cab"],
  },
  {
    slug: "bobcat-t450",
    brand: "Bobcat",
    model: "T450",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 1300,
    tippingLoad: 3714,
    engineHp: 55,
    operatingWeight: 6605,
    bucketWidth: 60,
    travelSpeed: 7.5,
    hydraulicFlow: 18.4,
    liftPath: "Radial",
    priceRange: "$55,000–$68,000",
    description: "Compact CTL ideal for soft ground, landscaping, and sites where wheeled machines leave ruts.",
    highlights: ["Rubber tracks standard", "Bob-Tach system", "Low ground pressure", "Excellent terrain traction"],
  },
  {
    slug: "bobcat-t550",
    brand: "Bobcat",
    model: "T550",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 1595,
    tippingLoad: 4557,
    engineHp: 60,
    operatingWeight: 7540,
    bucketWidth: 62,
    travelSpeed: 7.7,
    hydraulicFlow: 21.5,
    liftPath: "Radial",
    priceRange: "$64,000–$76,000",
    description: "Popular mid-frame CTL delivering excellent flotation and attachment compatibility on varied terrain.",
    highlights: ["7.7 mph top speed", "Selectable joystick controls", "High-flow available", "2-speed travel"],
  },
  {
    slug: "bobcat-t650",
    brand: "Bobcat",
    model: "T650",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2200,
    tippingLoad: 6286,
    engineHp: 74,
    operatingWeight: 9160,
    bucketWidth: 68,
    travelSpeed: 7.7,
    hydraulicFlow: 26.6,
    liftPath: "Radial",
    priceRange: "$75,000–$90,000",
    description: "Large-frame CTL with outstanding stability and multi-terrain performance for construction work.",
    highlights: ["74 HP diesel", "Ride Control standard", "Bob-Tach attachment system", "High-flow available"],
  },
  {
    slug: "bobcat-t740",
    brand: "Bobcat",
    model: "T740",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2600,
    tippingLoad: 7429,
    engineHp: 90,
    operatingWeight: 10420,
    bucketWidth: 72,
    travelSpeed: 7.7,
    hydraulicFlow: 30.6,
    liftPath: "Vertical",
    priceRange: "$90,000–$108,000",
    description: "High-capacity vertical-lift CTL for serious truck loading and material handling on soft terrain.",
    highlights: ["Vertical lift path", "30.6 gpm / 40.8 gpm HF", "Pressurized cab available", "Telematics ready"],
  },

  // ─── CATERPILLAR ─────────────────────────────────────────────────────────────
  {
    slug: "cat-226d3",
    brand: "Caterpillar",
    model: "226D3",
    type: "Skid Steer",
    ratedOperatingCapacity: 1300,
    tippingLoad: 2600,
    engineHp: 66,
    operatingWeight: 7620,
    bucketWidth: 72,
    travelSpeed: 7.5,
    hydraulicFlow: 16.5,
    liftPath: "Radial",
    priceRange: "$55,000–$68,000",
    description: "Cat's compact mid-frame skid steer built for versatility and ease of operation across general construction and site work.",
    highlights: ["Cat C2.4 engine", "Industry-leading cab visibility", "Cat Smart Technology ready", "ROPS/FOPS certified"],
  },
  {
    slug: "cat-232d3",
    brand: "Caterpillar",
    model: "232D3",
    type: "Skid Steer",
    ratedOperatingCapacity: 1900,
    tippingLoad: 3800,
    engineHp: 66,
    operatingWeight: 8082,
    bucketWidth: 72,
    travelSpeed: 7.5,
    hydraulicFlow: 16.5,
    liftPath: "Radial",
    priceRange: "$62,000–$76,000",
    description: "Cat mid-size skid steer balancing lifting capacity and engine power for demanding construction applications.",
    highlights: ["Cat Smart Technology", "Positive flow hydraulics", "High-flow option", "Premium cab ergonomics"],
  },
  {
    slug: "cat-242d3",
    brand: "Caterpillar",
    model: "242D3",
    type: "Skid Steer",
    ratedOperatingCapacity: 2200,
    tippingLoad: 4400,
    engineHp: 74,
    operatingWeight: 8330,
    bucketWidth: 72,
    travelSpeed: 7.5,
    hydraulicFlow: 23.0,
    liftPath: "Radial",
    priceRange: "$68,000–$82,000",
    description: "Large-frame Cat skid steer delivering strong ROC, versatile hydraulics, and outstanding jobsite uptime.",
    highlights: ["74 HP Cat C2.8T", "Cat Smart Technology", "High-flow XPS option", "Advanced touchscreen monitor"],
  },
  {
    slug: "cat-262d3",
    brand: "Caterpillar",
    model: "262D3",
    type: "Skid Steer",
    ratedOperatingCapacity: 2700,
    tippingLoad: 5400,
    engineHp: 74,
    operatingWeight: 8296,
    bucketWidth: 72,
    travelSpeed: 7.7,
    hydraulicFlow: 23.0,
    liftPath: "Vertical",
    priceRange: "$72,000–$88,000",
    description: "Cat's large vertical-lift skid steer — extended reach for quick truck loading and superior material handling.",
    highlights: ["Vertical lift design", "74.3 HP Cat engine", "High-flow XPS 32 gpm option", "Cat Smart Technology"],
  },
  {
    slug: "cat-260",
    brand: "Caterpillar",
    model: "260",
    type: "Skid Steer",
    ratedOperatingCapacity: 3160,
    tippingLoad: 6321,
    engineHp: 74,
    operatingWeight: 8523,
    bucketWidth: 72,
    travelSpeed: 7.7,
    hydraulicFlow: 20.0,
    liftPath: "Vertical",
    priceRange: "$80,000–$96,000",
    description: "Cat's newest large-frame skid steer — 13% more torque, advanced touchscreen, and vertical lift for peak productivity.",
    highlights: ["3,160 lb ROC (industry leading)", "8-inch Advanced Touchscreen", "C2.8T Tier 4 Final engine", "High-flow XPS 34 gpm option"],
  },
  {
    slug: "cat-299d3-xe",
    brand: "Caterpillar",
    model: "299D3 XE",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3560,
    tippingLoad: 10171,
    engineHp: 110,
    operatingWeight: 11756,
    bucketWidth: 84,
    travelSpeed: 10.5,
    hydraulicFlow: 40.0,
    liftPath: "Vertical",
    priceRange: "$100,000–$125,000",
    description: "Cat's premium large CTL — powerful engine, high-output hydraulics, and torsion axle suspension for demanding ground conditions.",
    highlights: ["110 HP Cat engine", "40 gpm high-flow XPS standard", "Torsion axle suspension", "Cat Smart Technology"],
  },
  {
    slug: "cat-275",
    brand: "Caterpillar",
    model: "275",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 4156,
    tippingLoad: 11874,
    engineHp: 111,
    operatingWeight: 12401,
    bucketWidth: 84,
    travelSpeed: 10.5,
    hydraulicFlow: 43.0,
    liftPath: "Vertical",
    priceRange: "$115,000–$140,000",
    description: "Cat's largest CTL — highest ROC in its class with vertical lift, powerful hydraulics, and E-bar undercarriage.",
    highlights: ["4,156 lb ROC", "111 HP Cat engine", "E-bar equalizer undercarriage", "2-speed 10.5 mph"],
  },

  // ─── JOHN DEERE ──────────────────────────────────────────────────────────────
  {
    slug: "jd-320-ptier",
    brand: "John Deere",
    model: "320 P-Tier",
    type: "Skid Steer",
    ratedOperatingCapacity: 2050,
    tippingLoad: 4100,
    engineHp: 68,
    operatingWeight: 6590,
    bucketWidth: 68,
    travelSpeed: 7.2,
    hydraulicFlow: 20.6,
    liftPath: "Radial",
    priceRange: "$52,000–$62,000",
    description: "Compact mid-frame skid steer with John Deere's legendary reliability and comprehensive dealer network.",
    highlights: ["JDLink telematics standard", "Worksite Pro attachment system", "Vertical lift available", "Comfort series cab"],
  },
  {
    slug: "jd-326-ptier",
    brand: "John Deere",
    model: "326 P-Tier",
    type: "Skid Steer",
    ratedOperatingCapacity: 2600,
    tippingLoad: 5200,
    engineHp: 82,
    operatingWeight: 8120,
    bucketWidth: 72,
    travelSpeed: 7.5,
    hydraulicFlow: 25.0,
    liftPath: "Vertical",
    priceRange: "$62,000–$75,000",
    description: "Large-frame skid steer delivering vertical lift reach and strong breakout force for construction sites.",
    highlights: ["Vertical lift path", "JDLink telematics", "82 HP Yanmar engine", "Auto-idle function"],
  },
  {
    slug: "jd-332-ptier",
    brand: "John Deere",
    model: "332 P-Tier",
    type: "Skid Steer",
    ratedOperatingCapacity: 3250,
    tippingLoad: 6500,
    engineHp: 100,
    operatingWeight: 10128,
    bucketWidth: 78,
    travelSpeed: 12.0,
    hydraulicFlow: 27.0,
    liftPath: "Vertical",
    priceRange: "$78,000–$96,000",
    description: "John Deere's flagship large-frame skid steer with two-speed travel and high-capacity vertical lift.",
    highlights: ["12 mph 2-speed", "100 HP engine", "JDLink telematics", "High-flow 37 gpm option"],
  },
  {
    slug: "jd-334-ptier",
    brand: "John Deere",
    model: "334 P-Tier",
    type: "Skid Steer",
    ratedOperatingCapacity: 4000,
    tippingLoad: 8000,
    engineHp: 118,
    operatingWeight: 10264,
    bucketWidth: 80,
    travelSpeed: 12.0,
    hydraulicFlow: 25.0,
    liftPath: "Vertical",
    priceRange: "$100,000–$125,000",
    msrp: 117805,
    description: "John Deere's most powerful skid steer — 118 HP Yanmar engine, class-leading ROC, and two-speed drive.",
    highlights: ["4,000 lb ROC", "118 HP Yanmar 4TNV94FHT", "JDLink telematics standard", "High-flow 44 gpm option"],
  },
  {
    slug: "jd-333-ptier",
    brand: "John Deere",
    model: "333 P-Tier",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3550,
    tippingLoad: 10143,
    engineHp: 100,
    operatingWeight: 11000,
    bucketWidth: 80,
    travelSpeed: 8.5,
    hydraulicFlow: 27.0,
    liftPath: "Vertical",
    priceRange: "$95,000–$115,000",
    description: "John Deere's large CTL — robust steel undercarriage, vertical lift, and high attachment productivity.",
    highlights: ["100 HP diesel", "JDLink telematics", "Vertical lift path", "High-flow 37 gpm option"],
  },
  {
    slug: "jd-335-ptier",
    brand: "John Deere",
    model: "335 P-Tier",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 4025,
    tippingLoad: 11500,
    engineHp: 118,
    operatingWeight: 12300,
    bucketWidth: 84,
    travelSpeed: 8.5,
    hydraulicFlow: 25.0,
    liftPath: "Vertical",
    priceRange: "$120,000–$148,000",
    msrp: 143639,
    description: "John Deere's largest CTL — exceptional lifting capacity, 118 HP, and class-leading ground pressure for soft terrain.",
    highlights: ["4,025 lb ROC", "118 HP Yanmar engine", "High-flow 44 gpm option", "JDLink telematics standard"],
  },

  // ─── CASE ────────────────────────────────────────────────────────────────────
  {
    slug: "case-sr160b",
    brand: "Case",
    model: "SR160B",
    type: "Skid Steer",
    ratedOperatingCapacity: 1600,
    tippingLoad: 3200,
    engineHp: 60,
    operatingWeight: 6180,
    bucketWidth: 64,
    travelSpeed: 7.2,
    hydraulicFlow: 20.0,
    liftPath: "Radial",
    priceRange: "$48,000–$58,000",
    description: "Case mid-frame skid steer with a no-rear-bar cab design for superior visibility and easy machine exit.",
    highlights: ["No rear door bar cab", "CASE SiteWatch telematics", "Electro-hydraulic controls", "Tier 4 Final engine"],
  },
  {
    slug: "case-sr210b",
    brand: "Case",
    model: "SR210B",
    type: "Skid Steer",
    ratedOperatingCapacity: 2100,
    tippingLoad: 4200,
    engineHp: 74,
    operatingWeight: 7500,
    bucketWidth: 68,
    travelSpeed: 7.5,
    hydraulicFlow: 23.0,
    liftPath: "Radial",
    priceRange: "$58,000–$70,000",
    description: "Case's popular radial-lift skid steer with outstanding cab visibility and efficient hydraulics.",
    highlights: ["Panoramic cab visibility", "CASE SiteWatch telematics", "Electronic foot pedal controls", "High-flow option"],
  },
  {
    slug: "case-sr250b",
    brand: "Case",
    model: "SR250B",
    type: "Skid Steer",
    ratedOperatingCapacity: 2500,
    tippingLoad: 5000,
    engineHp: 90,
    operatingWeight: 9200,
    bucketWidth: 72,
    travelSpeed: 7.8,
    hydraulicFlow: 25.0,
    liftPath: "Radial",
    priceRange: "$68,000–$82,000",
    description: "Large-frame Case skid steer with strong radial lift performance and broad attachment support.",
    highlights: ["90 HP engine", "SiteWatch fleet management", "Electronic controls", "Optional high-flow"],
  },
  {
    slug: "case-sv340b",
    brand: "Case",
    model: "SV340B",
    type: "Skid Steer",
    ratedOperatingCapacity: 3400,
    tippingLoad: 6800,
    engineHp: 100,
    operatingWeight: 10670,
    bucketWidth: 80,
    travelSpeed: 8.0,
    hydraulicFlow: 34.0,
    liftPath: "Vertical",
    priceRange: "$78,000–$95,000",
    description: "Case's flagship skid steer — vertical lift reach, 3,400 lb capacity, and premium cab comfort.",
    highlights: ["Vertical lift path", "100 HP diesel", "SiteWatch telematics", "Premium heated/cooled cab option"],
  },
  {
    slug: "case-tr270b",
    brand: "Case",
    model: "TR270B",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2700,
    tippingLoad: 7714,
    engineHp: 90,
    operatingWeight: 9870,
    bucketWidth: 72,
    travelSpeed: 8.0,
    hydraulicFlow: 25.0,
    liftPath: "Radial",
    priceRange: "$78,000–$94,000",
    description: "Case's mid-large CTL — radial lift, strong traction, and reliable performance on varied terrain.",
    highlights: ["90 HP engine", "Radial lift path", "SiteWatch telematics", "High-flow available"],
  },
  {
    slug: "case-tv380b",
    brand: "Case",
    model: "TV380B",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3800,
    tippingLoad: 10857,
    engineHp: 115,
    operatingWeight: 12250,
    bucketWidth: 84,
    travelSpeed: 8.5,
    hydraulicFlow: 34.0,
    liftPath: "Vertical",
    priceRange: "$92,000–$112,000",
    description: "Case's largest CTL — vertical lift, high capacity, and premium hydraulics for the most demanding applications.",
    highlights: ["3,800 lb ROC", "115 HP engine", "Vertical lift path", "SiteWatch fleet management"],
  },

  // ─── KUBOTA ──────────────────────────────────────────────────────────────────
  {
    slug: "kubota-ssv65",
    brand: "Kubota",
    model: "SSV65",
    type: "Skid Steer",
    ratedOperatingCapacity: 1540,
    tippingLoad: 3080,
    engineHp: 64,
    operatingWeight: 6600,
    bucketWidth: 64,
    travelSpeed: 7.4,
    hydraulicFlow: 18.5,
    liftPath: "Vertical",
    priceRange: "$48,000–$56,000",
    msrp: 51613,
    description: "Kubota's mid-size skid steer with smooth pilot controls and exceptional operator comfort.",
    highlights: ["64 HP Kubota diesel", "Pilot hydraulic controls", "Vertical lift path", "Wide-visibility cab"],
  },
  {
    slug: "kubota-ssv75",
    brand: "Kubota",
    model: "SSV75",
    type: "Skid Steer",
    ratedOperatingCapacity: 1800,
    tippingLoad: 3600,
    engineHp: 71.6,
    operatingWeight: 7100,
    bucketWidth: 68,
    travelSpeed: 7.4,
    hydraulicFlow: 21.9,
    liftPath: "Vertical",
    priceRange: "$55,000–$65,000",
    msrp: 59139,
    description: "Kubota's largest skid steer — refined pilot controls, strong ROC, and a best-in-class operator environment.",
    highlights: ["71.6 HP Kubota diesel", "Pilot hydraulic controls", "Exceptional cab visibility", "High-flow 30.4 gpm option"],
  },
  {
    slug: "kubota-svl65-2",
    brand: "Kubota",
    model: "SVL65-2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 1595,
    tippingLoad: 4557,
    engineHp: 64,
    operatingWeight: 7660,
    bucketWidth: 64,
    travelSpeed: 7.4,
    hydraulicFlow: 18.5,
    liftPath: "Radial",
    priceRange: "$62,000–$74,000",
    description: "Kubota's compact CTL — low ground pressure, smooth pilot controls, and exceptional reliability for landscaping and light construction.",
    highlights: ["Pilot controls standard", "64 HP Kubota diesel", "Low ground pressure tracks", "Easy service access"],
  },
  {
    slug: "kubota-svl75-2",
    brand: "Kubota",
    model: "SVL75-2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2690,
    tippingLoad: 7686,
    engineHp: 74,
    operatingWeight: 9590,
    bucketWidth: 72,
    travelSpeed: 7.4,
    hydraulicFlow: 24.8,
    liftPath: "Radial",
    priceRange: "$72,000–$86,000",
    description: "One of the best-selling CTLs in North America — praised for reliability, serviceability, and operator comfort.",
    highlights: ["74 HP Kubota diesel", "Pilot controls standard", "Excellent dealer network", "Pressurized ROPS cab option"],
  },
  {
    slug: "kubota-svl97-2",
    brand: "Kubota",
    model: "SVL97-2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3197,
    tippingLoad: 9134,
    engineHp: 96,
    operatingWeight: 11530,
    bucketWidth: 78,
    travelSpeed: 8.1,
    hydraulicFlow: 31.7,
    liftPath: "Radial",
    priceRange: "$88,000–$104,000",
    description: "Kubota's largest CTL — strong hydraulics, 96 HP, and a pressurized cab for the most productive heavy-duty jobsites.",
    highlights: ["96 HP Kubota diesel", "31.7 gpm / 39.0 gpm HF", "Pressurized ROPS cab", "Pilot hydraulic controls"],
  },

  // ─── NEW HOLLAND ─────────────────────────────────────────────────────────────
  {
    slug: "new-holland-l218",
    brand: "New Holland",
    model: "L218",
    type: "Skid Steer",
    ratedOperatingCapacity: 1700,
    tippingLoad: 3400,
    engineHp: 60,
    operatingWeight: 6230,
    bucketWidth: 64,
    travelSpeed: 7.1,
    hydraulicFlow: 17.4,
    liftPath: "Radial",
    priceRange: "$46,000–$56,000",
    description: "New Holland's compact skid steer — simple controls, durable construction, and easy daily maintenance.",
    highlights: ["60 HP FPT engine", "Electro-hydraulic controls", "ActivCare dealer support", "Easy-tilt cab"],
  },
  {
    slug: "new-holland-l228",
    brand: "New Holland",
    model: "L228",
    type: "Skid Steer",
    ratedOperatingCapacity: 2200,
    tippingLoad: 4400,
    engineHp: 66,
    operatingWeight: 6990,
    bucketWidth: 68,
    travelSpeed: 7.1,
    hydraulicFlow: 20.2,
    liftPath: "Radial",
    priceRange: "$54,000–$64,000",
    description: "New Holland's mid-frame workhorse — reliable FPT diesel and comprehensive attachment compatibility.",
    highlights: ["66 HP FPT diesel", "ActivCare dealer support", "Electro-hydraulic joystick", "Attachment interchangeability"],
  },
  {
    slug: "new-holland-l334",
    brand: "New Holland",
    model: "L334",
    type: "Skid Steer",
    ratedOperatingCapacity: 3300,
    tippingLoad: 6600,
    engineHp: 97,
    operatingWeight: 10120,
    bucketWidth: 80,
    travelSpeed: 7.8,
    hydraulicFlow: 32.0,
    liftPath: "Vertical",
    priceRange: "$80,000–$96,000",
    description: "New Holland's flagship skid steer — vertical lift, 3,300 lb capacity, and high-flow hydraulics standard.",
    highlights: ["Vertical lift path", "97 HP FPT engine", "32 gpm high-flow standard", "Premium panoramic cab"],
  },
  {
    slug: "new-holland-c237",
    brand: "New Holland",
    model: "C237",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2690,
    tippingLoad: 7686,
    engineHp: 74,
    operatingWeight: 9700,
    bucketWidth: 72,
    travelSpeed: 6.8,
    hydraulicFlow: 22.0,
    liftPath: "Radial",
    priceRange: "$68,000–$82,000",
    description: "New Holland's popular mid-frame CTL — strong reach height, easy-tilt cab, and SmartTrax undercarriage.",
    highlights: ["74 HP FPT diesel", "Easy-tilt cab", "SmartTrax steel undercarriage", "ActivCare telematics"],
  },
  {
    slug: "new-holland-c327",
    brand: "New Holland",
    model: "C327",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3200,
    tippingLoad: 9143,
    engineHp: 97,
    operatingWeight: 11500,
    bucketWidth: 80,
    travelSpeed: 7.8,
    hydraulicFlow: 32.0,
    liftPath: "Vertical",
    priceRange: "$88,000–$106,000",
    description: "New Holland's large CTL — vertical lift, high-flow hydraulics, and a premium pressurized cab option.",
    highlights: ["97 HP FPT engine", "Vertical lift path", "32 gpm high-flow standard", "SmartTrax undercarriage"],
  },

  // ─── GEHL ────────────────────────────────────────────────────────────────────
  {
    slug: "gehl-v420",
    brand: "Gehl",
    model: "V420",
    type: "Skid Steer",
    ratedOperatingCapacity: 2000,
    tippingLoad: 4000,
    engineHp: 57,
    operatingWeight: 5590,
    bucketWidth: 64,
    travelSpeed: 6.5,
    hydraulicFlow: 17.0,
    liftPath: "Vertical",
    priceRange: "$40,000–$50,000",
    description: "Compact vertical-lift skid steer ideal for budget-conscious buyers needing a reliable all-around machine.",
    highlights: ["Vertical lift path", "57 HP diesel", "Budget-friendly entry point", "Broad attachment ecosystem"],
  },
  {
    slug: "gehl-v340",
    brand: "Gehl",
    model: "V340",
    type: "Skid Steer",
    ratedOperatingCapacity: 3400,
    tippingLoad: 6800,
    engineHp: 100,
    operatingWeight: 10500,
    bucketWidth: 78,
    travelSpeed: 8.1,
    hydraulicFlow: 29.0,
    liftPath: "Vertical",
    priceRange: "$70,000–$84,000",
    description: "Gehl's largest skid steer — high capacity, vertical lift, and a full-feature cab for heavy construction.",
    highlights: ["100 HP diesel", "3,400 lb ROC", "Vertical lift path", "Ride Control available"],
  },

  // ─── TAKEUCHI ─────────────────────────────────────────────────────────────────
  {
    slug: "takeuchi-tl8r2",
    brand: "Takeuchi",
    model: "TL8R2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2149,
    tippingLoad: 6140,
    engineHp: 74,
    operatingWeight: 9480,
    bucketWidth: 68,
    travelSpeed: 7.6,
    hydraulicFlow: 22.6,
    liftPath: "Radial",
    priceRange: "$72,000–$86,000",
    description: "Takeuchi's mid-frame CTL — Japanese engineering, radial lift, and a reputation for outstanding durability.",
    highlights: ["74 HP Deutz engine", "Radial lift path", "Auto-idle and auto-shift", "Best-in-class serviceability"],
  },
  {
    slug: "takeuchi-tl12r2",
    brand: "Takeuchi",
    model: "TL12R2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3197,
    tippingLoad: 9134,
    engineHp: 96,
    operatingWeight: 12360,
    bucketWidth: 78,
    travelSpeed: 7.9,
    hydraulicFlow: 30.2,
    liftPath: "Radial",
    priceRange: "$90,000–$108,000",
    description: "Takeuchi's largest CTL — powerful hydraulics, radial lift, and exceptional operator comfort for heavy-duty applications.",
    highlights: ["96 HP Deutz diesel", "30.2 gpm / 42.0 gpm HF", "Auto-idle and auto-shift", "Steel or rubber track options"],
  },
]

export const brands = [...new Set(machines.map((m) => m.brand))].sort()
export const types: MachineType[] = ["Skid Steer", "Compact Track Loader"]
