export type MachineType = "Skid Steer" | "Compact Track Loader"

export interface SkidSteer {
  slug: string
  brand: string
  model: string
  type: MachineType
  ratedOperatingCapacity: number // lbs
  tippingLoad: number // lbs
  engineHp: number
  operatingWeight: number // lbs
  bucketWidth: number // inches
  travelSpeed: number // mph
  hydraulicFlow: number // gpm
  priceRange: string
  description: string
  highlights: string[]
}

export const machines: SkidSteer[] = [
  {
    slug: "bobcat-s76",
    brand: "Bobcat",
    model: "S76",
    type: "Skid Steer",
    ratedOperatingCapacity: 2690,
    tippingLoad: 5380,
    engineHp: 74,
    operatingWeight: 7820,
    bucketWidth: 72,
    travelSpeed: 7.1,
    hydraulicFlow: 23.4,
    priceRange: "$55,000–$65,000",
    description: "The Bobcat S76 is a large-frame skid steer delivering high lifting capacity and torque for demanding jobsites.",
    highlights: ["Selectable joystick controls", "Bob-Tach attachment system", "Pressurized cab option"],
  },
  {
    slug: "bobcat-s650",
    brand: "Bobcat",
    model: "S650",
    type: "Skid Steer",
    ratedOperatingCapacity: 2200,
    tippingLoad: 4400,
    engineHp: 66,
    operatingWeight: 7005,
    bucketWidth: 68,
    travelSpeed: 6.9,
    hydraulicFlow: 20.3,
    priceRange: "$47,000–$56,000",
    description: "A mid-size workhorse with proven Bobcat reliability and a wide attachment ecosystem.",
    highlights: ["Vertical lift path", "Enhanced visibility cab", "Attachment Control System"],
  },
  {
    slug: "bobcat-t76",
    brand: "Bobcat",
    model: "T76",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2690,
    tippingLoad: 5380,
    engineHp: 74,
    operatingWeight: 9885,
    bucketWidth: 72,
    travelSpeed: 6.9,
    hydraulicFlow: 23.4,
    priceRange: "$65,000–$78,000",
    description: "Track version of the S76 — superior flotation on soft or sensitive ground.",
    highlights: ["Rubber tracks standard", "Bob-Tach system", "High-flow hydraulics option"],
  },
  {
    slug: "cat-262d3",
    brand: "Caterpillar",
    model: "262D3",
    type: "Skid Steer",
    ratedOperatingCapacity: 2350,
    tippingLoad: 4700,
    engineHp: 74,
    operatingWeight: 7760,
    bucketWidth: 72,
    travelSpeed: 7.3,
    hydraulicFlow: 25.5,
    priceRange: "$56,000–$68,000",
    description: "Cat's mid-large frame skid steer with industry-leading visibility and Smart Technology ready.",
    highlights: ["Cat Smart Technology", "Positive flow hydraulics", "ROPS/FOPS cab"],
  },
  {
    slug: "cat-299xd3",
    brand: "Caterpillar",
    model: "299 XD3",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3600,
    tippingLoad: 7200,
    engineHp: 110,
    operatingWeight: 12480,
    bucketWidth: 84,
    travelSpeed: 8.7,
    hydraulicFlow: 40.0,
    priceRange: "$90,000–$110,000",
    description: "Cat's largest CTL — built for maximum productivity in the toughest conditions.",
    highlights: ["Cat Smart Technology", "High-flow/high-pressure hydraulics", "Premium suspension undercarriage"],
  },
  {
    slug: "cat-272d3",
    brand: "Caterpillar",
    model: "272D3",
    type: "Skid Steer",
    ratedOperatingCapacity: 3000,
    tippingLoad: 6000,
    engineHp: 90,
    operatingWeight: 9330,
    bucketWidth: 78,
    travelSpeed: 7.5,
    hydraulicFlow: 32.5,
    priceRange: "$70,000–$83,000",
    description: "Large-frame Cat skid steer with radial lift and heavy-duty performance.",
    highlights: ["Radial lift linkage", "Electronic control module", "Optional high flow"],
  },
  {
    slug: "jd-332g",
    brand: "John Deere",
    model: "332 G",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3550,
    tippingLoad: 7100,
    engineHp: 100,
    operatingWeight: 11580,
    bucketWidth: 80,
    travelSpeed: 8.5,
    hydraulicFlow: 36.0,
    priceRange: "$82,000–$98,000",
    description: "John Deere's flagship CTL — refined power, telematics, and legendary dealer support.",
    highlights: ["JDLink telematics", "Worksite Pro attachments", "Comfort series cab"],
  },
  {
    slug: "jd-320g",
    brand: "John Deere",
    model: "320 G",
    type: "Skid Steer",
    ratedOperatingCapacity: 2050,
    tippingLoad: 4100,
    engineHp: 68,
    operatingWeight: 6590,
    bucketWidth: 68,
    travelSpeed: 7.2,
    hydraulicFlow: 20.6,
    priceRange: "$48,000–$57,000",
    description: "A compact mid-frame skid steer with vertical lift and John Deere's proven powertrain.",
    highlights: ["Vertical lift path", "JDLink telematics", "Worksite Pro compatibility"],
  },
  {
    slug: "jd-326g",
    brand: "John Deere",
    model: "326 G",
    type: "Skid Steer",
    ratedOperatingCapacity: 2600,
    tippingLoad: 5200,
    engineHp: 82,
    operatingWeight: 8120,
    bucketWidth: 72,
    travelSpeed: 7.5,
    hydraulicFlow: 25.0,
    priceRange: "$58,000–$70,000",
    description: "Large-frame skid steer with vertical lift path and strong breakout force.",
    highlights: ["Vertical lift", "Deluxe cab available", "Auto-idle function"],
  },
  {
    slug: "case-sr270",
    brand: "Case",
    model: "SR270",
    type: "Skid Steer",
    ratedOperatingCapacity: 2700,
    tippingLoad: 5400,
    engineHp: 90,
    operatingWeight: 8700,
    bucketWidth: 72,
    travelSpeed: 7.5,
    hydraulicFlow: 25.0,
    priceRange: "$57,000–$68,000",
    description: "Case's large-frame radial-lift skid steer with best-in-class visibility and a no-bar cab.",
    highlights: ["No rear door bar cab", "Electronic foot pedal controls", "CASE SiteWatch telematics"],
  },
  {
    slug: "case-tr340b",
    brand: "Case",
    model: "TR340B",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3400,
    tippingLoad: 6800,
    engineHp: 100,
    operatingWeight: 11230,
    bucketWidth: 80,
    travelSpeed: 8.2,
    hydraulicFlow: 34.0,
    priceRange: "$80,000–$96,000",
    description: "High-capacity CTL with radial lift for digging, loading, and grading on tough terrain.",
    highlights: ["Radial lift path", "High-flow hydraulics", "CASE SiteWatch telematics"],
  },
  {
    slug: "case-sv340b",
    brand: "Case",
    model: "SV340B",
    type: "Skid Steer",
    ratedOperatingCapacity: 3400,
    tippingLoad: 6800,
    engineHp: 100,
    operatingWeight: 10600,
    bucketWidth: 80,
    travelSpeed: 8.0,
    hydraulicFlow: 34.0,
    priceRange: "$75,000–$88,000",
    description: "Case's largest skid steer with vertical lift and exceptional reach height.",
    highlights: ["Vertical lift path", "Premium cab with heat/cool", "SiteWatch fleet management"],
  },
  {
    slug: "kubota-ssv75",
    brand: "Kubota",
    model: "SSV75",
    type: "Skid Steer",
    ratedOperatingCapacity: 2690,
    tippingLoad: 5380,
    engineHp: 74,
    operatingWeight: 7782,
    bucketWidth: 72,
    travelSpeed: 7.1,
    hydraulicFlow: 21.9,
    priceRange: "$50,000–$62,000",
    description: "Kubota's large-frame skid steer with smooth controls and a comfortable operator environment.",
    highlights: ["Pilot hydraulic controls", "Wide-open cab visibility", "Kubota Diesel engine"],
  },
  {
    slug: "kubota-svl75-2",
    brand: "Kubota",
    model: "SVL75-2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2690,
    tippingLoad: 5380,
    engineHp: 74,
    operatingWeight: 9590,
    bucketWidth: 72,
    travelSpeed: 7.4,
    hydraulicFlow: 24.8,
    priceRange: "$62,000–$74,000",
    description: "One of the best-selling CTLs — praised for reliability, serviceability, and operator comfort.",
    highlights: ["Tier 4 Final engine", "Pilot controls standard", "Excellent dealer network"],
  },
  {
    slug: "kubota-svl97-2",
    brand: "Kubota",
    model: "SVL97-2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3197,
    tippingLoad: 6394,
    engineHp: 96,
    operatingWeight: 11530,
    bucketWidth: 78,
    travelSpeed: 8.1,
    hydraulicFlow: 31.7,
    priceRange: "$76,000–$90,000",
    description: "Kubota's largest CTL — strong hydraulics and lifting capacity with a smooth ride.",
    highlights: ["96 HP Kubota diesel", "High-flow hydraulics", "Pressurized ROPS cab"],
  },
  {
    slug: "new-holland-l228",
    brand: "New Holland",
    model: "L228",
    type: "Skid Steer",
    ratedOperatingCapacity: 2200,
    tippingLoad: 4400,
    engineHp: 66,
    operatingWeight: 6990,
    bucketWidth: 68,
    travelSpeed: 7.1,
    hydraulicFlow: 20.2,
    priceRange: "$46,000–$55,000",
    description: "New Holland's mid-frame skid steer — simple, durable, and easy to service.",
    highlights: ["Electro-hydraulic controls", "ActivCare dealer support", "Powerstar engine"],
  },
  {
    slug: "new-holland-c237",
    brand: "New Holland",
    model: "C237",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 2690,
    tippingLoad: 5380,
    engineHp: 74,
    operatingWeight: 9700,
    bucketWidth: 72,
    travelSpeed: 6.8,
    hydraulicFlow: 22.0,
    priceRange: "$60,000–$73,000",
    description: "Reliable CTL with strong reach height and easy daily maintenance access.",
    highlights: ["Radial lift", "Easy-tilt cab", "SmartTrax undercarriage"],
  },
  {
    slug: "new-holland-l334",
    brand: "New Holland",
    model: "L334",
    type: "Skid Steer",
    ratedOperatingCapacity: 3300,
    tippingLoad: 6600,
    engineHp: 97,
    operatingWeight: 10120,
    bucketWidth: 80,
    travelSpeed: 7.8,
    hydraulicFlow: 32.0,
    priceRange: "$72,000–$86,000",
    description: "New Holland's large-frame flagship skid steer with vertical lift and top-tier capacity.",
    highlights: ["Vertical lift path", "High-flow standard", "Dual-function auxiliary hydraulics"],
  },
  {
    slug: "gehl-v420",
    brand: "Gehl",
    model: "V420",
    type: "Skid Steer",
    ratedOperatingCapacity: 2000,
    tippingLoad: 4000,
    engineHp: 57,
    operatingWeight: 5590,
    bucketWidth: 64,
    travelSpeed: 6.5,
    hydraulicFlow: 17.0,
    priceRange: "$38,000–$46,000",
    description: "Compact and maneuverable — the Gehl V420 punches above its weight in tight spaces.",
    highlights: ["Small footprint", "Budget-friendly entry point", "Vertical lift"],
  },
  {
    slug: "takeuchi-tl12r2",
    brand: "Takeuchi",
    model: "TL12R2",
    type: "Compact Track Loader",
    ratedOperatingCapacity: 3197,
    tippingLoad: 6394,
    engineHp: 96,
    operatingWeight: 12360,
    bucketWidth: 78,
    travelSpeed: 7.9,
    hydraulicFlow: 30.2,
    priceRange: "$78,000–$92,000",
    description: "Takeuchi's largest CTL with excellent hydraulic performance and operator comfort.",
    highlights: ["Radial lift", "Auto-idle and auto-shift", "Steel or rubber track options"],
  },
]

export const brands = [...new Set(machines.map((m) => m.brand))].sort()
export const types: MachineType[] = ["Skid Steer", "Compact Track Loader"]
